name: Docker Package

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  PROJECT: kubescope

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Set variables
        run: |
          REPOSITORY="${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.PROJECT }}"

          echo "REPOSITORY=$REPOSITORY" >> $GITHUB_ENV
          echo "TAG_RELEASE=$REPOSITORY:${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          echo "TAG_LATEST=$REPOSITORY:latest" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Packages registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          #tags: ${{ env.TAG_RELEASE }},${{ env.TAG_LATEST }
          tags: ${{ env.REPOSITORY }}:dispatch-${{ github.run_number }}
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=registry,ref=${{ env.REPOSITORY }}:buildcache
          cache-to: type=registry,ref=${{ env.REPOSITORY }}:buildcache,mode=max
